name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        
    - name: Install backend dependencies
      run: |
        cd backend
        npm install
        
    - name: Verify backend files
      run: |
        ls -la backend/
        cat backend/package.json
        
    - name: Start backend server
      run: |
        cd backend
        npm start &
        echo "Server started with PID $!"
        sleep 10
        
    - name: Test API endpoints
      run: |
        echo "Testing API endpoints..."
        curl -v http://localhost:5000/ || echo "Root endpoint failed"
        curl -v http://localhost:5000/api/ideas || echo "Ideas endpoint failed"
        
    - name: Stop background processes
      run: |
        pkill -f "node server.js" || true
        
    - name: Test frontend files exist
      run: |
        ls -la .
        test -f index.html
        test -f app.js
        test -f styles.css

  build:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Create deployment artifact
      run: |
        tar -czf idea-manager.tar.gz backend/ index.html app.js styles.css start.sh README.md LICENSE package.json
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: idea-manager-build
        path: idea-manager.tar.gz
